# Generated by Django 3.2.2 on 2021-05-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
