# Generated by Django 3.2.2 on 2021-05-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_todolistitem_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
