# Generated by Django 3.2.2 on 2021-05-17 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0005_alter_todolistitem_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 10, 39, 44, 509791, tzinfo=utc)),
        ),
    ]
